name: Pull Request
description: Template for pull requests
body:
  - type: markdown
    attributes:
      value: |
        ## Pull Request
        
        Please ensure your pull request adheres to the following guidelines:
  
  - type: input
    id: title
    attributes:
      label: PR Title
      description: Please provide a clear title for your pull request.
      placeholder: "[TITLE] - "
      validations:
      required: true
  
  - type: textarea
    id: description
    attributes:
      label: PR Description
      description: Provide a clear and concise description of what your pull request does.
      placeholder: "Describe the changes in detail..."
      validations:
      required: true
  
  - type: input
    id: related_issue
    attributes:
      label: Related Issue
      description: If applicable, reference the issue that this PR addresses.
      placeholder: "Fixes #123"
      validations:
      required: true
  
  - type: textarea
    id: changes_made
    attributes:
      label: Changes Made
      description: List out the changes you made in this PR.
      placeholder: "- Change 1\n- Change 2"
      validations:
      required: true
  
  - type: file
    id: demo_upload
    attributes:
      label: Demo Upload
      description: Upload a demo video or photo of your changes in action.
      fileType: ["video/*", "image/*"]
      validations:
      required: true
  
  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context about the pull request or additional notes.
      placeholder: "Additional context..."
