name: StandOut-Platform Feature Request
description: Create a new Feature Request for StandOut-Platform
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the sections below to properly describe the new feature you are suggesting.

  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: Description
      placeholder: |
        A brief description of your idea

  - type: textarea
    id: goals
    validations:
      required: true
    attributes:
      label: Goals
      description: List the goals of the feature.
      placeholder: |
        - Goal 1
        - Goal 2

  - type: textarea
    id: implementation-details
    validations:
      required: true
    attributes:
      label: Implementation Details
      description: List any technical details about the proposed implementation, including any specific technologies that will be used.
      placeholder: |
        - Implementation Detail 1
        - Implementation Detail 2
        - also add images if possible

  - type: dropdown
    id: skills-required
    attributes:
      label: Tech Skills Needed
      description: Select the technologies needed for this ticket (use Ctrl or Command to select multiple)
      multiple: true
      options:
        - Flask
        - HTML
        - CSS
        - JavaScript
        - Other
    validations:
      required: true

  - type: dropdown
    id: category
    attributes: 
      label: Category
      description: Choose the categories that best describe your ticket
      multiple: true
      options:
        - API
        - Backend
        - Database
        - Documentation
        - Deployment
        - Frontend
        - Testing
        - UI
        - UX
        - Other
    validations:
      required: true